services:
  erigon:
    image: erigontech/erigon:v3.5.4
    restart: unless-stopped
    network_mode: host
    mem_swappiness: 0
    volumes:
      - /mnt/nvme4TB2/erigon:/home/erigon/.local/share/erigon
      - /mnt/nvme4TB2/erigon/jwt.hex:/secrets/jwt.hex:ro
      - ./erigon.yaml:/etc/erigon/erigon.yaml:ro
    command: --config=/etc/erigon/erigon.yaml
