services:
  erigon:
    image: erigontech/erigon:v3.4.3
    restart: unless-stopped
    network_mode: host
    volumes:
      - /mnt/nvme4TB2/erigon:/home/erigon/.local/share/erigon
      - /mnt/nvme4TB2/erigon/jwt.hex:/secrets/jwt.hex:ro
      - ./erigon.yaml:/etc/erigon/erigon.yaml:ro
    command: erigon --config=/etc/erigon/erigon.yaml
